name: sentiment-analysis-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pandas=1.5.3
  - scikit-learn=1.2.1
  - nltk=3.7
  - langdetect=1.0.9
  - deep-translator=1.9.0
  - pillow=9.0.1
  - pip:
    - streamlit==1.19.0
